### ISSUE TITLE
Implementing ResNet using Firefly

### ISSUE THREAD

**Issue by vignesh99** [klightz/Firefly#2]
Hello @klightz and @Cranial-XIX,
I want to implement the ResNet (Eg: PreActResNet-18) using Firefly. I see that you guys have put the code only for VGGNet and MobileNet. So firstly, is it possible to grow ResNets using Firefly? 

If so, since the ResNet contains a PreActBlock, I cannot directly modify your VGG code to get a ResNet. I am unsure of defining a new class (sp.PreActBlock) since the sp.Conv2d class is very intricate and I don't know which all functions (`spf_reset`, `spf_update`, `spf_forward`... so on) to carry over from that to the new class. 

If you have a Firefly code for ResNet, can you please share it? If not, can you suggest how to go about growing a ResNet using Firefly?

For example:
```
class PreActBlock(nn.Module):
    '''Pre-activation version of the BasicBlock.'''
    expansion = 1

    def __init__(self, in_planes, planes, stride=1, Conv2d = nn.Conv2d, BatchNorm2d = nn.BatchNorm2d):
        super(PreActBlock, self).__init__()
        self.bn1 = BatchNorm2d(in_planes)
        self.conv1 = sp.Conv2d(in_planes, planes, kernel_size=3, stride=stride, padding=1, bias=False)
        self.bn2 = BatchNorm2d(planes)
        self.conv2 = sp.Conv2d(planes, planes, kernel_size=3, stride=1, padding=1, bias=False)

        if stride != 1 or in_planes != self.expansion*planes:
            self.shortcut = nn.Sequential(
                Conv2d(in_planes, self.expansion*planes, kernel_size=1, stride=stride, bias=False)
            )

    def forward(self, x):
        out = F.relu(self.bn1(x))
        shortcut = self.shortcut(out) if hasattr(self, 'shortcut') else x
        out = self.conv1(out)
        out = self.conv2(F.relu(self.bn2(out)))
        out += shortcut
        return out
```
In the above case, I have kept everything same as the original PreActBlock, but only replaced `nn.Conv2d` to `sp.Conv2d`. Is this sufficient to make it work?

**Comment by vignesh99** [comment]
Hello @klightz and @Cranial-XIX,
I do not see any code for growing the networks deeper using Identity mapping and so on here. You have done experiments on growing the network deeper as indicated in Appendix B.2. of your paper. 
Can you please update the repository with that code, or if it already exists here, please point me to that?

**Comment by klightz** [comment]
Hello, regarding the implementation of ResNet, there is no official implementation available. One of the main challenges lies in effectively handling the residual connections. These connections require a width adjustment module when adding width to different layers. Unfortunately, we have not yet developed a suitable approach to address this issue to achieve optimal performance.

For the deeper growth network, we did not clean up that code as it was part of an appendix experiment and the results did not demonstrate significant improvement compared to the baseline models. Also, that old experiment code is a little bit hard to find. I can try to search and see if I have any raw code for this part to send you.

**Comment by vignesh99** [comment]
Since the width does not change once the architecture is fixed, i.e., since the width does not change between WideResNet-18-2 or ResNet-18, can it not be implemented for a fixed width? For example, just ResNet-18 network (width=1)?

Please do provide me whatever code that is available with you for growing deeper networks as soon as you can, it will be very helpful.
